// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for carrossel documents
 */
interface CarrosselDocumentData {
  /**
   * prop field in *carrossel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carrossel.prop
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  prop: prismic.ImageField<never>;

  /**
   * prop1 field in *carrossel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carrossel.prop1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  prop1: prismic.ImageField<never>;

  /**
   * prop2 field in *carrossel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carrossel.prop2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  prop2: prismic.ImageField<never>;

  /**
   * prop3 field in *carrossel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carrossel.prop3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  prop3: prismic.ImageField<never>;

  /**
   * prop4 field in *carrossel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carrossel.prop4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  prop4: prismic.ImageField<never>;
}

/**
 * carrossel document from Prismic
 *
 * - **API ID**: `carrossel`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CarrosselDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CarrosselDocumentData>,
    "carrossel",
    Lang
  >;

export type AllDocumentTypes = CarrosselDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type { CarrosselDocument, CarrosselDocumentData, AllDocumentTypes };
  }
}
