// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * prop field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.prom
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  prom: prismic.ImageField<never>;

  /**
   * prop1 field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.prom1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  prom1: prismic.ImageField<never>;

  /**
   * prop2 field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.prom2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  prom2: prismic.ImageField<never>;

  /**
   * prop3 field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.prom3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  prom3: prismic.ImageField<never>;

  /**
   * prop4 field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.prom4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  prom4: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type { HomeDocument, HomeDocumentData, AllDocumentTypes };
  }
}
